---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{.Values.msname}}-{{.Values.felabel}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: {{.Values.msname}}
      tier: {{.Values.felabel}}
  replicas: 2
  minReadySeconds: 5
  progressDeadlineSeconds: 300
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:
      labels:
        app: {{.Values.msname}}
        tier: {{.Values.felabel}}
    spec:
      containers:
      - name: myappfe
        image: mohanraz81/myapp-frontend:13.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: {{.Values.limits.cpu | quote}}
            memory: {{.Values.limits.memory | quote}}
          requests:
            cpu: "0.2"
            memory: "200Mi"
        env:
          - name: "MY_DB_USER"
            value: "mysqluser"
          - name: "MY_DB_PASS"
            value: "password"
          - name: "MY_DB_NAME"
            value: "mydatadb"
          - name: "MY_DB_HOST_WRITE"
            value: "mysql-0.mysql"
          - name: "MY_DB_HOST_READ"
            value: "mysql-read"



