---
version: "3.7"
services:
  myapp-frontend:
    build:
      context: ./myappfrontend
    image: mohanraz81/mycart-frontend:2.0
    depends_on:
      - myapp-backend
    environment:
      BACKENDLB: myapp-backend
    ports:
      - "9000:80"
    volumes:
      - type: volume
        source: myapp-frontend-logvol
        target: /var/log
  myapp-backend:
    build:
      context: ./myappbackend
    image: mohanraz81/mycart-backend:2.0
    volumes:
      - type: volume
        source: myapp-backend-logvol
        target: /var/log
  myapp-db:
    image: mysql:5.7
    volumes:
      - type: volume
        source: myapp-db-vol
        target: /var/lib/mysql
volumes:
  myapp-frontend-logvol:
  myapp-backend-logvol:
  myapp-db-vol:
